---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.io.weli
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.io.weli
  resources:
  - guestbooks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.io.weli
  resources:
  - guestbooks/status
  verbs:
  - get
  - patch
  - update
